#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Rebuild the puddle fork's patch stack on a new upstream msb release (fork-only file).

Used by .github/workflows/puddle-autobump.yml. Builds everything locally and pushes nothing:

* msb: every commit on the fork branch since its upstream base, replayed on the new release tag
  per .github/puddle/stack.txt (pick / regenerate / drop), ending in a version commit for
  <release>-puddle.N.
* libkrun leg: when the release pins a newer msb_krun than the fork's libkrun branch is based on,
  the libkrun fork's commits are replayed on that version's commit into branch puddle-<version>.
* russh leg: when the release's Cargo.lock resolves another russh than the fork's russh branch is
  based on, the russh fork's commits are replayed on that tag into branch puddle-<version>.

Legs are built in local clones that cargo reaches through `url.<clone>.insteadOf`, so the new
Cargo.lock pins the exact commits that a later push publishes. Output in --work: report.json,
summary.md, msb.bundle (+ libkrun.bundle, russh.bundle) and candidate.json for the gate jobs.
Exit code: 0 replayed, 3 conflict or stack error (summary says what), 1 crash.
"""

import argparse
import datetime
import json
import os
import re
import subprocess
import sys
from pathlib import Path

LIBKRUN_URL = "https://github.com/TijsVK/libkrun"
LIBKRUN_UPSTREAM = "https://github.com/superradcompany/libkrun"
LIBKRUN_UPSTREAM_BRANCH = "krun"
RUSSH_URL = "https://github.com/TijsVK/russh"
RUSSH_UPSTREAM = "https://github.com/Eugeny/russh"
MARKER = "# puddle fork: patched dependencies (generated by .github/puddle/replay.py)."
BOT = ("puddle auto-bump", "puddle@tijsvankampen.be")


class StackError(Exception):
    """The replay stops here; the message goes into the summary/issue."""


def run(args, cwd=None, check=True, env=None, capture=True):
    p = subprocess.run(args, cwd=cwd, env=env, text=True,
                       stdout=subprocess.PIPE if capture else None,
                       stderr=subprocess.PIPE if capture else None)
    if check and p.returncode != 0:
        raise RuntimeError(f"{' '.join(args)} (in {cwd}) exited {p.returncode}:\n{p.stdout}\n{p.stderr}")
    return p


def git(repo, *args, check=True, env=None):
    return run(["git", *args], cwd=repo, check=check, env=env)


def out(repo, *args):
    return git(repo, *args).stdout.strip()


def semver(v):
    m = re.fullmatch(r"(\d+)\.(\d+)\.(\d+)", v)
    if not m:
        raise StackError(f"not a plain version: {v}")
    return tuple(int(x) for x in m.groups())


def bot_env(extra=None):
    env = dict(os.environ)
    env.update({"GIT_COMMITTER_NAME": BOT[0], "GIT_COMMITTER_EMAIL": BOT[1]})
    if extra:
        env.update(extra)
    return env


def author_env():
    return bot_env({"GIT_AUTHOR_NAME": BOT[0], "GIT_AUTHOR_EMAIL": BOT[1]})


# ------------------------------------------------------------------------------------ manifest
def load_manifest(path):
    rules = []
    for n, line in enumerate(Path(path).read_text().splitlines(), 1):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        cols = [c.strip() for c in line.split(" | ")]
        if len(cols) != 4:
            raise StackError(f"{path}:{n}: want 4 columns separated by ' | ', got {len(cols)}")
        action, match, folder, upstream = cols
        if action not in ("pick", "krun", "russh", "version") and not action.startswith("rm:"):
            raise StackError(f"{path}:{n}: unknown action {action}")
        rules.append({"line": n, "action": action, "match": match, "folder": folder, "upstream": upstream})
    return rules


def rule_for(rules, subject):
    for r in rules:
        m = r["match"]
        if (m.endswith("*") and subject.startswith(m[:-1])) or subject == m:
            return r
    return None


# --------------------------------------------------------------------------------- cargo helpers
def cargo_toml_pin(text, crate):
    m = re.search(rf'^{re.escape(crate)} = "=([^"]+)"', text, re.M)
    return m.group(1) if m else None


def lock_versions(text, name):
    return re.findall(rf'\[\[package\]\]\nname = "{re.escape(name)}"\nversion = "([^"]+)"', text)


def lock_registry_packages(text, prefix):
    names = set()
    for m in re.finditer(r'\[\[package\]\]\nname = "([^"]+)"\nversion = "[^"]+"\nsource = "([^"]+)"', text):
        if m.group(1).startswith(prefix):
            names.add(m.group(1))
    return sorted(names)


def patch_lines_for(text, url):
    """Crate names that a Cargo.toml patches to `url`."""
    return sorted(set(re.findall(rf'^([A-Za-z0-9_-]+) = \{{ git = "{re.escape(url)}"', text, re.M)))


def cargo_refresh(repo, gitconfig):
    """Let cargo rewrite Cargo.lock for the manifest; fail on an unused [patch]."""
    # Own CARGO_HOME: cargo's GitHub fast path asks api.github.com for a branch head and skips the
    # fetch when its git db already has that commit, which would pin the old fork commit instead of
    # the replayed one when a leg rebuilds a branch name that exists on GitHub.
    env = dict(os.environ, CARGO_NET_GIT_FETCH_WITH_CLI="true", GIT_CONFIG_GLOBAL=str(gitconfig),
               CARGO_HOME=str(Path(gitconfig).parent / "cargo-home"))
    p = run(["cargo", "metadata", "--format-version", "1", "--manifest-path", "Cargo.toml"],
            cwd=repo, env=env, check=False)
    if p.returncode != 0:
        raise StackError(f"cargo metadata failed:\n{p.stderr[-3000:]}")
    unused = [l for l in p.stderr.splitlines() if "was not used in the crate graph" in l]
    if unused:
        raise StackError("a [patch.crates-io] entry is unused (the fix would silently not ship):\n" +
                         "\n".join(unused))


def render_patch_section(krun, russh):
    if not krun and not russh:
        return ""
    lines = ["", MARKER]
    if krun:
        lines.append(f"# libkrun: TijsVK/libkrun branch {krun['branch']} = msb_krun {krun['base_version']} "
                     f"plus the puddle libkrun fixes.")
    if russh:
        lines.append(f"# russh: TijsVK/russh branch {russh['branch']} = russh {russh['base_version']} "
                     f"plus the puddle russh fix.")
    lines.append("# One branch per base version, so older fork tags stay buildable.")
    lines.append("[patch.crates-io]")
    for leg, url in ((krun, LIBKRUN_URL), (russh, RUSSH_URL)):
        if leg:
            for crate in leg["crates"]:
                lines.append(f'{crate} = {{ git = "{url}", branch = "{leg["branch"]}" }}')
    return "\n".join(lines) + "\n"


def write_cargo_toml(repo, krun, russh, pin):
    path = Path(repo) / "Cargo.toml"
    text = path.read_text()
    if MARKER in text:
        text = text[: text.index(MARKER)].rstrip("\n") + "\n"
    if "[patch.crates-io]" in text:
        raise StackError("upstream's Cargo.toml has its own [patch.crates-io]; replay.py must learn to merge it")
    if pin:
        for crate in ("msb_krun", "msb_krun_utils"):
            text, n = re.subn(rf'^({crate} = "=)[^"]+(")', rf"\g<1>{pin}\g<2>", text, flags=re.M)
            if n != 1:
                raise StackError(f'Cargo.toml: expected one `{crate} = "=..."` line, found {n}')
    path.write_text(text.rstrip("\n") + "\n" + render_patch_section(krun, russh))


def write_version(repo, old, new):
    path = Path(repo) / "Cargo.toml"
    text = path.read_text()
    text, n1 = re.subn(rf'^version = "{re.escape(old)}"$', f'version = "{new}"', text, count=1, flags=re.M)
    text, n2 = re.subn(rf'"={re.escape(old)}"', f'"={new}"', text)
    if n1 != 1 or n2 == 0:
        raise StackError(f"Cargo.toml: workspace version {old} not found ({n1} version lines, {n2} = pins)")
    path.write_text(text)
    return n2


# ------------------------------------------------------------------------------------ cherry-pick
def unmerged(repo):
    return [l[3:] for l in out(repo, "status", "--porcelain").splitlines()
            if l[:2] in ("UU", "AA", "DU", "UD", "AU", "UA", "DD")]


def pick(repo, sha, lock_ok=False, gitconfig=None):
    """Cherry-pick; returns 'picked', 'empty' or raises StackError on a conflict."""
    p = git(repo, "cherry-pick", "--allow-empty", "--keep-redundant-commits", sha, check=False, env=bot_env())
    if p.returncode == 0:
        if out(repo, "rev-parse", "HEAD^{tree}") == out(repo, "rev-parse", "HEAD~1^{tree}"):
            git(repo, "reset", "-q", "--hard", "HEAD~1")
            return "empty"
        return "picked"
    files = unmerged(repo)
    if files and lock_ok and set(files) <= {"Cargo.lock"}:
        git(repo, "checkout", "--ours", "--", "Cargo.lock")
        cargo_refresh(repo, gitconfig)
        git(repo, "add", "Cargo.lock")
        git(repo, "-c", "core.editor=true", "cherry-pick", "--continue", env=bot_env())
        return "picked"
    if not files and git(repo, "diff", "--cached", "--quiet", check=False).returncode == 0:
        git(repo, "cherry-pick", "--skip", check=False)
        return "empty"
    detail = git(repo, "diff", check=False).stdout[:6000]
    git(repo, "cherry-pick", "--abort", check=False)
    raise StackError(f"conflict replaying {sha[:12]} `{out(repo, 'log', '-1', '--format=%s', sha)}` "
                     f"in: {', '.join(files) or '(none listed)'}\n\n```diff\n{detail}\n```")


# ---------------------------------------------------------------------------------------- legs
def ensure_clone(path, url, upstream_url):
    if not (path / ".git").exists():
        run(["git", "clone", "-q", "--no-checkout", url, str(path)])
        git(path, "remote", "add", "upstream", upstream_url)
        git(path, "remote", "set-url", "--push", "upstream", "DISABLED")
    git(path, "fetch", "-q", "origin")
    git(path, "config", "user.name", BOT[0])
    git(path, "config", "user.email", BOT[1])


def replay_leg(path, base, commits, branch):
    git(path, "checkout", "-q", "-f", "-B", branch, base)
    kept, dropped = [], []
    for c in commits:
        subj = out(path, "log", "-1", "--format=%s", c)
        r = pick(path, c)
        (kept if r == "picked" else dropped).append(subj)
    return out(path, "rev-parse", "HEAD"), kept, dropped


def krun_base_for(path, version):
    """Commit of superradcompany/libkrun that msb_krun <version> was published from."""
    try:
        import io, tarfile, urllib.request
        req = urllib.request.Request(f"https://static.crates.io/crates/msb_krun/msb_krun-{version}.crate",
                                     headers={"User-Agent": "puddle-autobump (puddle@tijsvankampen.be)"})
        data = urllib.request.urlopen(req, timeout=60).read()
        with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as t:
            info = json.load(t.extractfile(f"msb_krun-{version}/.cargo_vcs_info.json"))
        sha = info["git"]["sha1"]
        git(path, "fetch", "-q", "upstream", sha)
        return sha, "crates.io .cargo_vcs_info.json"
    except Exception as e:  # unpublished (as 0.1.41 was) or no vcs info: find the bump commit
        git(path, "fetch", "-q", "upstream", LIBKRUN_UPSTREAM_BRANCH)
        for c in out(path, "rev-list", "--reverse", f"upstream/{LIBKRUN_UPSTREAM_BRANCH}", "--",
                     "src/krun/Cargo.toml").splitlines():
            if re.search(rf'^version = "{re.escape(version)}"$',
                         out(path, "show", f"{c}:src/krun/Cargo.toml"), re.M):
                return c, f"first krun commit with src/krun/Cargo.toml version {version} ({e.__class__.__name__} on crates.io)"
        raise StackError(f"no superradcompany/libkrun commit found for msb_krun {version}")


def krun_version_at(path, rev):
    m = re.search(r'^version = "([^"]+)"$', out(path, "show", f"{rev}:src/krun/Cargo.toml"), re.M)
    return m.group(1)


def libkrun_leg(args, cur_toml, new_lock, up_pin):
    cur_branch = re.search(rf'git = "{re.escape(LIBKRUN_URL)}", branch = "([^"]+)"', cur_toml)
    if not cur_branch:
        return None, {"leg": "libkrun", "state": "not wired"}
    cur_branch = cur_branch.group(1)
    path = Path(args.work) / "libkrun"
    ensure_clone(path, LIBKRUN_URL, LIBKRUN_UPSTREAM)
    git(path, "fetch", "-q", "upstream", LIBKRUN_UPSTREAM_BRANCH)
    cur_tip = out(path, "rev-parse", f"origin/{cur_branch}")
    cur_base = out(path, "merge-base", cur_tip, f"upstream/{LIBKRUN_UPSTREAM_BRANCH}")
    cur_ver = krun_version_at(path, cur_base)
    commits = out(path, "rev-list", "--reverse", "--no-merges", f"{cur_base}..{cur_tip}").splitlines()
    crates = lock_registry_packages(new_lock, "msb_krun")
    info = {"leg": "libkrun", "current_branch": cur_branch, "current_base": cur_base,
            "current_version": cur_ver, "release_pin": up_pin}
    moved = semver(up_pin) > semver(cur_ver)
    if not moved and not args.force_legs:
        info["state"] = "unchanged"
        return {"branch": cur_branch, "sha": cur_tip, "base_version": cur_ver, "pin": cur_ver,
                "crates": crates, "local": False}, info
    target = up_pin if moved else cur_ver
    base, how = (krun_base_for(path, target) if moved else (cur_base, "current base (forced)"))
    branch = f"puddle-{target}"
    tip, kept, dropped = replay_leg(path, base, commits, branch)
    info.update({"state": "replayed", "branch": branch, "base": base, "base_found_by": how,
                 "kept": kept, "dropped": dropped, "sha": tip,
                 "tree_equal_to_current": out(path, "rev-parse", f"{tip}^{{tree}}") ==
                 out(path, "rev-parse", f"{cur_tip}^{{tree}}")})
    if not kept:
        info["state"] = "all fixes upstream: patch dropped"
        return None, info
    return {"branch": branch, "sha": tip, "base": base, "base_version": target, "pin": target,
            "crates": crates, "local": True, "path": str(path)}, info


def russh_leg(args, cur_toml, new_lock):
    m = re.search(rf'git = "{re.escape(RUSSH_URL)}", branch = "puddle-([^"]+)"', cur_toml)
    if not m:
        return None, {"leg": "russh", "state": "not wired"}
    cur_ver = m.group(1)
    cur_branch = f"puddle-{cur_ver}"
    crates = patch_lines_for(cur_toml, RUSSH_URL)
    vers = lock_versions(new_lock, "russh")
    if len(vers) != 1:
        raise StackError(f"release Cargo.lock has {len(vers)} russh versions ({vers}); expected one")
    rel = vers[0]
    path = Path(args.work) / "russh"
    ensure_clone(path, RUSSH_URL, RUSSH_UPSTREAM)
    git(path, "fetch", "-q", "upstream", "tag", f"v{cur_ver}", "--no-tags")
    cur_tip = out(path, "rev-parse", f"origin/{cur_branch}")
    info = {"leg": "russh", "current_branch": cur_branch, "current_version": cur_ver, "release_lock": rel}
    if rel == cur_ver and not args.force_legs:
        info["state"] = "unchanged"
        return {"branch": cur_branch, "sha": cur_tip, "base_version": cur_ver, "crates": crates,
                "local": False}, info
    commits = out(path, "rev-list", "--reverse", "--no-merges", f"v{cur_ver}..{cur_tip}").splitlines()
    git(path, "fetch", "-q", "upstream", "tag", f"v{rel}", "--no-tags")
    base = out(path, "rev-parse", f"v{rel}^{{commit}}")
    branch = f"puddle-{rel}"
    tip, kept, dropped = replay_leg(path, base, commits, branch)
    info.update({"state": "replayed", "branch": branch, "base": base, "kept": kept, "dropped": dropped,
                 "sha": tip, "tree_equal_to_current": out(path, "rev-parse", f"{tip}^{{tree}}") ==
                 out(path, "rev-parse", f"{cur_tip}^{{tree}}")})
    if not kept:
        info["state"] = "fix upstream: patch dropped"
        return None, info
    return {"branch": branch, "sha": tip, "base": base, "base_version": rel, "crates": crates,
            "local": True, "path": str(path)}, info


# ------------------------------------------------------------------------------------------ main
def message(subject, body):
    return subject + "\n\n" + body.strip() + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=".")
    ap.add_argument("--stack-ref", default="origin/puddle")
    ap.add_argument("--upstream-tag", required=True, help="release tag name, e.g. v0.7.8")
    ap.add_argument("--upstream-sha", required=True)
    ap.add_argument("--version", required=True, help="fork version, e.g. 0.7.8-puddle.1")
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--work", required=True)
    ap.add_argument("--force-legs", action="store_true", help="replay libkrun/russh even if their base did not move")
    ap.add_argument("--inject-conflict", action="store_true", help="dry-run test: make the first fix conflict")
    args = ap.parse_args()

    repo = Path(args.repo).resolve()
    work = Path(args.work).resolve()
    work.mkdir(parents=True, exist_ok=True)
    args.work = str(work)
    gitconfig = work / "gitconfig"
    gitconfig.write_text("")
    report = {"upstream_tag": args.upstream_tag, "upstream_sha": args.upstream_sha, "version": args.version,
              "picked": [], "dropped": [], "regenerated": [], "legs": [], "status": "error"}
    try:
        replay(args, repo, work, gitconfig, report)
        report["status"] = "ok"
        code = 0
    except StackError as e:
        report["status"] = "conflict"
        report["error"] = str(e)
        code = 3
    (work / "report.json").write_text(json.dumps(report, indent=2))
    (work / "summary.md").write_text(summary(report))
    print(summary(report))
    return code


def replay(args, repo, work, gitconfig, report):
    rules = load_manifest(args.manifest)
    prev_tag = out(repo, "describe", "--tags", "--first-parent", "--abbrev=0", "--match", "v*-puddle.*", args.stack_ref)
    prev_base_tag = prev_tag.split("-puddle.")[0]
    prev_base = out(repo, "rev-parse", f"{prev_base_tag}^{{commit}}")
    if git(repo, "merge-base", "--is-ancestor", prev_base, args.stack_ref, check=False).returncode != 0:
        raise StackError(f"{prev_base_tag} is not an ancestor of {args.stack_ref}")
    stack = out(repo, "rev-list", "--reverse", "--first-parent", "--no-merges", f"{prev_base}..{args.stack_ref}").splitlines()
    report.update({"previous_tag": prev_tag, "previous_base": prev_base_tag, "stack_ref": out(repo, "rev-parse", args.stack_ref),
                   "stack_size": len(stack)})

    plan, unknown = [], []
    for c in stack:
        subj = out(repo, "log", "-1", "--format=%s", c)
        r = rule_for(rules, subj)
        if r is None:
            unknown.append(f"{c[:12]} {subj}")
        plan.append((c, subj, r))
    if unknown:
        raise StackError("commits on the fork branch that no line in .github/puddle/stack.txt matches "
                         "(add them, then rerun):\n" + "\n".join(f"- {u}" for u in unknown))
    exact = [r for r in rules if not r["match"].endswith("*")]
    seen = {id(r) for _, _, r in plan}
    report["manifest_not_on_branch"] = [r["match"] for r in exact if id(r) not in seen]

    up = args.upstream_sha
    up_toml = out(repo, "show", f"{up}:Cargo.toml")
    up_lock = out(repo, "show", f"{up}:Cargo.lock") + "\n"
    up_version = re.search(r'^\[workspace\.package\]\n(?:(?!\[)[^\n]*\n)*?version = "([^"]+)"', up_toml, re.M).group(1)
    want_release = re.sub(r"^.*?v(\d+\.\d+\.\d+)$", r"\1", args.upstream_tag)
    if up_version != want_release:
        report["warning"] = f"workspace version at {args.upstream_tag} is {up_version}, not {want_release}"
    up_pin = cargo_toml_pin(up_toml, "msb_krun")
    cur_toml = out(repo, "show", f"{args.stack_ref}:Cargo.toml")
    report["release"] = {"workspace_version": up_version, "msb_krun_pin": up_pin,
                         "russh_lock": lock_versions(up_lock, "russh")}

    krun = russh = None
    if any(r and r["action"] == "krun" for _, _, r in plan):
        krun, info = libkrun_leg(args, cur_toml, up_lock, up_pin)
        report["legs"].append(info)
    if any(r and r["action"] == "russh" for _, _, r in plan):
        russh, info = russh_leg(args, cur_toml, up_lock)
        report["legs"].append(info)
    cfg = []
    for leg, url in ((krun, LIBKRUN_URL), (russh, RUSSH_URL)):
        if leg and leg["local"]:
            cfg.append(f'[url "file://{leg["path"]}"]\n\tinsteadOf = {url}\n')
    gitconfig.write_text("".join(cfg))

    git(repo, "checkout", "-q", "-f", "--detach", up)
    git(repo, "clean", "-qfdx", "-e", ".scratch")
    if args.inject_conflict:
        inject_conflict(repo, plan)

    applied_krun = applied_russh = None
    version_extra = []
    date = datetime.date.today().isoformat()
    for c, subj, r in plan:
        action = r["action"]
        if r["upstream"] != "-" and upstream_merged(repo, r["upstream"], up):
            report["dropped"].append({"commit": subj, "why": f"{r['upstream']} merged into {args.upstream_tag}"})
            continue
        if action == "pick":
            touches_lock = "Cargo.lock" in out(repo, "show", "--name-only", "--format=", c).splitlines()
            res = pick(repo, c, lock_ok=True, gitconfig=gitconfig)
            entry = {"commit": subj, "folder": r["folder"]}
            if res == "empty":
                report["dropped"].append({**entry, "why": "empty on the new base (already upstream)"})
            else:
                if touches_lock:
                    cargo_refresh(repo, gitconfig)
                    if git(repo, "diff", "--quiet", check=False).returncode != 0:
                        git(repo, "commit", "-q", "-a", "--amend", "--no-edit", env=bot_env())
                report["picked"].append(entry)
        elif action.startswith("rm:"):
            path = action[3:]
            if (repo / path).exists():
                git(repo, "rm", "-q", "--", path)
                git(repo, "commit", "-q", "-C", c, env=bot_env())
                report["picked"].append({"commit": subj, "folder": "-"})
            else:
                report["dropped"].append({"commit": subj, "why": f"{path} not in {args.upstream_tag}"})
        elif action == "version":
            version_extra.append(c)
        elif action in ("krun", "russh"):
            if (action == "krun" and applied_krun) or (action == "russh" and applied_russh):
                # A later commit that moved the same leg (e.g. a new fork commit in Cargo.lock):
                # the leg's single regenerated commit already pins the branch's current tip.
                report["dropped"].append({"commit": subj, "why": f"folded into the regenerated {action} commit"})
                continue
            if action == "krun":
                applied_krun = krun
            else:
                applied_russh = russh
            pin = (applied_krun or {}).get("pin") or up_pin
            write_cargo_toml(repo, applied_krun, applied_russh, pin)
            cargo_refresh(repo, gitconfig)
            if git(repo, "status", "--porcelain", check=False).stdout.strip() == "":
                report["dropped"].append({"commit": subj, "why": "no patch needed any more"})
                continue
            git(repo, "add", "Cargo.toml", "Cargo.lock")
            leg = applied_krun if action == "krun" else applied_russh
            msg = leg_message(action, leg, krun, russh, args.upstream_tag, date, report)
            commit_msg(repo, msg)
            report["regenerated"].append(msg.splitlines()[0])

    # Version commit: other files of the version commits (e.g. the PREBUILT_VERSION suffix strip),
    # then the workspace version and the internal `=` pins.
    for c in version_extra:
        files = [f for f in out(repo, "show", "--name-only", "--format=", c).splitlines()
                 if f not in ("Cargo.toml", "Cargo.lock")]
        if files:
            p = run(["git", "format-patch", "-1", "--stdout", c, "--", *files], cwd=repo)
            a = subprocess.run(["git", "apply", "--3way", "--index"], cwd=repo, input=p.stdout, text=True,
                               capture_output=True)
            if a.returncode != 0:
                raise StackError(f"version commit {c[:12]}: its {', '.join(files)} change does not apply:\n{a.stderr}")
    n = write_version(repo, up_version, args.version)
    cargo_refresh(repo, gitconfig)
    git(repo, "add", "-A", "--", ".", ":!.scratch")
    msg = message(f"build: version the puddle fork as {args.version}", f"""
puddle's bundled-runtime check reads the version embedded in msb.exe and accepts exactly
<release>-puddle.N, and the SDK only takes the modern launch contract when msb's version equals its
own. So the workspace version and the internal crates' exact pins ({n}) carry the fork tag's
version: {args.version} for tag v{args.version}.

PREBUILT_VERSION drops the pre-release suffix, so the build scripts and setup still fetch agentd and
the runtime bundle from the upstream {args.upstream_tag} release.

Regenerated by .github/puddle/replay.py for {args.upstream_tag}.

Change note (Apache-2.0 section 4(b)): this commit modifies Cargo.toml, Cargo.lock and
crates/utils/lib/lib.rs. Changed for the puddle fork by its auto-bump job, {date}.""")
    commit_msg(repo, msg)
    report["regenerated"].append(msg.splitlines()[0])

    tip = out(repo, "rev-parse", "HEAD")
    git(repo, "branch", "-f", "puddle-candidate", tip)
    report["tip"] = tip
    report["diff_vs_stack_ref"] = out(repo, "diff", "--stat", args.stack_ref, tip)
    # Merge commit for the `puddle` branch: the new stack as first parent (so the next replay
    # walks it with --first-parent) and the old branch as second, tree = new stack.
    merge = out(repo, "commit-tree", f"{tip}^{{tree}}", "-p", tip, "-p", out(repo, "rev-parse", args.stack_ref),
                "-m", f"Merge the puddle stack on {args.upstream_tag} ({args.version})\n\n"
                      f"Tree = v{args.version}. The old branch is the second parent, so `puddle` moves\n"
                      f"forward without a force push.")
    git(repo, "branch", "-f", "puddle-candidate-merge", merge)
    report["merge"] = merge

    # msb.bundle needs only the release commit (gate jobs); msb-merge.bundle also the old branch.
    bundles = {"msb": {"bundle": "msb.bundle", "merge_bundle": "msb-merge.bundle", "sha": tip, "merge": merge,
                       "base": up, "old": out(repo, "rev-parse", args.stack_ref)}}
    git(repo, "bundle", "create", str(work / "msb.bundle"), "puddle-candidate", f"^{up}")
    git(repo, "bundle", "create", str(work / "msb-merge.bundle"), "puddle-candidate-merge", "^puddle-candidate",
        f"^{bundles['msb']['old']}")
    for name, leg, url in (("libkrun", applied_krun, LIBKRUN_URL), ("russh", applied_russh, RUSSH_URL)):
        if leg and leg["local"]:
            git(leg["path"], "bundle", "create", str(work / f"{name}.bundle"), f"refs/heads/{leg['branch']}", f"^{leg['base']}")
            bundles[name] = {"bundle": f"{name}.bundle", "url": url, "branch": leg["branch"], "sha": leg["sha"],
                             "base": leg["base"], "base_url": LIBKRUN_UPSTREAM if name == "libkrun" else RUSSH_UPSTREAM,
                             "base_version": leg["base_version"]}
    (work / "candidate.json").write_text(json.dumps(bundles, indent=2))
    report["candidate"] = bundles


def commit_msg(repo, msg):
    subprocess.run(["git", "commit", "-q", "-F", "-"], cwd=repo, input=msg, text=True, check=True, env=author_env())


def leg_message(action, leg, krun, russh, upstream_tag, date, report):
    if action == "krun":
        info = next(i for i in report["legs"] if i["leg"] == "libkrun")
        fixes = info.get("kept") or []
        body = f"""
Pin msb_krun and msb_krun_utils to ={leg['pin']} and take every msb_krun_* crate from
TijsVK/libkrun branch `{leg['branch']}` ({leg['sha'][:12]}) through [patch.crates-io]. That branch is
msb_krun {leg['base_version']} plus the puddle libkrun fixes{':' if fixes else '.'}
""" + "".join(f"- {f}\n" for f in fixes) + f"""
Regenerated by .github/puddle/replay.py for {upstream_tag} (libkrun leg: {info['state']}).

Change note (Apache-2.0 section 4(b)): this commit modifies Cargo.toml and Cargo.lock. Changed for
the puddle fork by its auto-bump job, {date}."""
        return message(f"build: use the puddle libkrun fork (msb_krun {leg['pin']})", body)
    info = next(i for i in report["legs"] if i["leg"] == "russh")
    body = f"""
[patch.crates-io] takes {', '.join(leg['crates'])} from TijsVK/russh branch `{leg['branch']}`
({leg['sha'][:12]}): russh {leg['base_version']} plus the fix for the session wedge when the peer
closes a channel with queued data (puddle upstream-issues/russh-peer-close-pending-data-wedge/).

Regenerated by .github/puddle/replay.py for {upstream_tag} (russh leg: {info['state']}).

Change note (Apache-2.0 section 4(b)): this commit modifies Cargo.toml and Cargo.lock. Changed for
the puddle fork by its auto-bump job, {date}."""
    return message(f"build: use the puddle russh fork ({leg['base_version']} with the peer-close fix)", body)


def upstream_merged(repo, ref, up):
    m = re.fullmatch(r"([\w.-]+/[\w.-]+)#(\d+)", ref)
    if not m:
        raise StackError(f"stack.txt upstream column: want owner/repo#N, got {ref}")
    p = run(["gh", "api", f"repos/{m.group(1)}/pulls/{m.group(2)}", "--jq", ".merge_commit_sha + \" \" + (.merged|tostring)"],
            check=False)
    if p.returncode != 0:
        return False
    sha, merged = (p.stdout.strip().split() + ["", ""])[:2]
    if merged != "true":
        return False
    git(repo, "fetch", "-q", f"https://github.com/{m.group(1)}", sha, check=False)
    return git(repo, "merge-base", "--is-ancestor", sha, up, check=False).returncode == 0


def inject_conflict(repo, plan):
    """Dry-run test only: change, on the new base, a line that the first fix also changes."""
    for c, subj, r in plan:
        if r["action"] != "pick":
            continue
        diff = out(repo, "show", "--format=", "-U0", c)
        f = re.search(r"^\+\+\+ b/(.+)$", diff, re.M)
        h = re.search(r"^@@ -(\d+)", diff, re.M)
        if not f or not h:
            continue
        path, line = Path(repo) / f.group(1), max(int(h.group(1)), 1)
        lines = path.read_text().splitlines(keepends=True)
        lines[line - 1] = "// puddle auto-bump dry run: forced conflict\n" + lines[line - 1]
        path.write_text("".join(lines))
        git(repo, "commit", "-q", "-am", "test: forced conflict (auto-bump dry run only)", env=author_env())
        return
    raise StackError("inject-conflict: no pick commit to conflict with")


def summary(rep):
    s = [f"### Replay of the puddle stack on `{rep['upstream_tag']}` as `{rep['version']}`: **{rep['status']}**", ""]
    if rep.get("previous_tag"):
        s.append(f"Previous fork tag `{rep['previous_tag']}` (base `{rep['previous_base']}`), "
                 f"{rep.get('stack_size', '?')} commits on the branch since that base.")
    if rep.get("release"):
        r = rep["release"]
        s.append(f"Release: workspace version {r['workspace_version']}, msb_krun pin ={r['msb_krun_pin']}, "
                 f"russh in Cargo.lock {', '.join(r['russh_lock'])}.")
    if rep.get("warning"):
        s.append(f"\n**Warning:** {rep['warning']}")
    if rep.get("error"):
        s += ["", "**Stopped:**", "", rep["error"]]
    if rep["picked"]:
        s += ["", "Picked:"] + [f"- {p['commit']}" + (f" ({p['folder']})" if p.get("folder", "-") != "-" else "") for p in rep["picked"]]
    if rep["dropped"]:
        s += ["", "Dropped:"] + [f"- {d['commit']}: {d['why']}" for d in rep["dropped"]]
    if rep["regenerated"]:
        s += ["", "Regenerated:"] + [f"- {r}" for r in rep["regenerated"]]
    for leg in rep["legs"]:
        s += ["", f"{leg['leg']} leg: **{leg['state']}**" + "".join(
            f"; {k} `{v}`" for k, v in leg.items() if k in ("current_branch", "current_version", "release_pin",
                                                          "release_lock", "branch", "base", "sha", "base_found_by",
                                                          "tree_equal_to_current"))]
        if leg.get("kept") is not None:
            s += [f"  - kept: {k}" for k in leg["kept"]] + [f"  - dropped (empty): {d}" for d in leg.get("dropped", [])]
    if rep.get("manifest_not_on_branch"):
        s += ["", "stack.txt lines with no commit on the branch: " + "; ".join(rep["manifest_not_on_branch"])]
    if rep.get("tip"):
        s += ["", f"New stack tip `{rep['tip']}`, merge commit for `puddle` `{rep['merge']}`.", "",
              "Tree difference against the current fork branch:", "", "```", rep["diff_vs_stack_ref"] or "(none)", "```"]
    return "\n".join(s) + "\n"


if __name__ == "__main__":
    sys.exit(main())
